# ===============================================================
# 
# Release under GPLv2.
# 
# @file    Makefile
# @brief   
# @author  gnsyxiang <gnsyxiang@163.com>
# @date    22/12 2018 17:56
# @version v0.0.1
# 
# @since    note
# @note     note
# 
#     change log:
#     NO.     Author              Date            Modified
#     00      zhenquan.qiu        22/12 2018      create the file
# 
#     last modified: 22/12 2018 17:56
# ===============================================================

TO_TOP_DIR 	:= ..

include $(TO_TOP_DIR)/configs/com-var-def.mk

GCC_VERSION := gcc-arm-none-eabi-5_4-2016q3-20160926

GCC_SRC_VERSION := $(GCC_VERSION)-src.tar.bz2
GCC_BIN_VERSION := $(GCC_VERSION)-linux.tar.bz2

all:
	$(TAR_BZ) $(GCC_SRC_VERSION)

